# Generated by Django 3.1.8 on 2021-04-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_book', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('cpf', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Moviments',
            fields=[
                ('id_moviment', models.AutoField(primary_key=True, serialize=False)),
                ('date_lent', models.TimeField(blank=True, null=True)),
                ('date_returned', models.TimeField(blank=True, null=True)),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
            options={
                'verbose_name': 'Moviment',
                'verbose_name_plural': 'Moviments',
            },
        ),
    ]
