# Generated by Django 3.1.8 on 2021-04-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moviments',
            new_name='BookReservations',
        ),
    ]
