# Generated by Django 3.1.8 on 2021-04-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210421_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreservations',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
    ]
