# Generated by Django 3.1.8 on 2021-04-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210421_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreservations',
            old_name='id_moviment',
            new_name='id_reservation',
        ),
    ]
