# Generated by Django 3.1.8 on 2021-04-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210421_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.BooleanField(blank=True, choices=[(1, 'disponível'), (2, 'emprestado')], default=1, null=True),
        ),
    ]
