# Generated by Django 3.1.8 on 2021-04-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210422_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.BooleanField(blank=True, choices=[(True, 'disponível'), (False, 'emprestado')], null=True),
        ),
    ]
