# Generated by Django 3.1.8 on 2021-04-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210422_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreservations',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
