# Generated by Django 3.1.8 on 2021-04-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bookreservations_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreservations',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
