# Generated by Django 3.1.8 on 2021-04-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210425_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreservations',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
